### ISSUE TITLE
This widget only support  model？

### ISSUE THREAD

**Issue by nadirvishun** [kartik-v/yii2-widget-switchinput#29] opened 2017-04-26 01:09 UTC
This widget only support  model？
I want use checkbox without model，but the status of checked is associated with options's config value，so when post to form ,it can not post right value,why designed this?
in kartik\base\IputWidget.php :
````
protected function getInput($type, $list = false)
    {
       //if has model
        if ($this->hasModel()) {
            $input = 'active' . ucfirst($type);
            return $list ?
                Html::$input($this->model, $this->attribute, $this->data, $this->options) :
                Html::$input($this->model, $this->attribute, $this->options);
        }
     // if there no model
        $input = $type;
        $checked = false;
        if ($type == 'radio' || $type == 'checkbox') {//the radio tyep do not used this function ,only checkbox use 
            $this->options['value'] = $this->value;
            $checked = ArrayHelper::remove($this->options, 'checked', '');
            if (empty($checked) && !empty($this->value)) {
                $checked = ($this->value == 0) ? false : true;//why checked status definde by $this->value
            } elseif (empty($checked)) {
                $checked = false;
            }
        }
        return $list ?
            Html::$input($this->name, $this->value, $this->data, $this->options) :
            (($type == 'checkbox' || $type == 'radio') ?
                Html::$input($this->name, $checked, $this->options) :
                Html::$input($this->name, $this->value, $this->options));
    }
````
I want to do like this without model ：
````
 $tag = SwitchInput::widget([
                    'name' => $name,
                    'value' => 1,//default 1
                    'options' => ['uncheck' => 0,'checked'=>$value],//has hidden input,and checked status by db value
                    'pluginOptions' => ['size' => 'small']
                ]);
````
if change like blow ,it will work 
````
protected function getInput($type, $list = false)
    {
       //if has model
        if ($this->hasModel()) {
            $input = 'active' . ucfirst($type);
            return $list ?
                Html::$input($this->model, $this->attribute, $this->data, $this->options) :
                Html::$input($this->model, $this->attribute, $this->options);
        }
     // if there no model
        $input = $type;
        $checked = false;
        if ($type == 'radio' || $type == 'checkbox') {
            $this->options['value'] = $this->value;//not necessary,in widget config options value can also work
            $checked = ArrayHelper::remove($this->options, 'checked', '');
           // if (empty($checked) && !empty($this->value)) {
          //      $checked = ($this->value == 0) ? false : true
          //  } else
           if (empty($checked)) {
                $checked = false;
            }
        }
        return $list ?
            Html::$input($this->name, $this->value, $this->data, $this->options) :
            (($type == 'checkbox' || $type == 'radio') ?
                Html::$input($this->name, $checked, $this->options) :
                Html::$input($this->name, $this->value, $this->options));
    }
````
.How to resove it?

**Comment by kartik-v** [comment] 2017-04-26 01:49
Not sure of what the problem is. In all Yii Input Widgets the `value` property is used directly to pass the value when using WITHOUT model.

All you need is just directly pass the `SwitchInput::value` property and set it to `0` for unchecked and `1` for checked.

**Comment by nadirvishun** [comment] 2017-04-26 03:31
if I have this html: 
````
<input type="hidden" name='abc'  value="0">
<input type="checkbox" name ='abc' value="1" <?= $value==1?"checked":""?> >
````
I can use db $value to change checked status.
when post to php , if  click checked ,I can get the post:
````
abc=1
```` 
if I not click ,I can get the hidden value
```
abc=0
```
but,in this widget I set:
````
echo SwitchInput::widget([
                    'name' => 'abc',
                    'value' => '1',//this value not only the value,but also affect to check status
                    'options' => ['uncheck' => 0],
                ]);
````
it convert html is
````
<input type="hidden" name='abc'  value="0">
<input type="checkbox" name ='abc' value="1" checked ><!--it auto checked because value set 1-->
````
but maybe my db value is 0 ,it should not checked .if i change value to 0,like this:
````
echo SwitchInput::widget([
                    'name' => 'abc',
                    'value' => '0',//this value not only the value,but also affect to check status
                    'options' => ['uncheck' => 1],
                ]);
````
it convert html is
````
<input type="hidden" name='abc'  value="1">
<input type="checkbox" name ='abc' value="0"  >
````
then if I checkd and post to form ,I receive
````
abc=0
```` 
but I checked ,I want get abc=1.
totally,the value affect checked status,and I can not get the real post data.

**Comment by kartik-v** [comment] 2017-04-26 05:50
It is simple.

Do not set the `options['uncheck']` when you are using SwitchInput without model.

This way no hidden input will be generated.

**Comment by nadirvishun** [comment] 2017-04-26 08:08
@kartik-v 
this is not good way to solve the problem.
if do like as you say ,I have to write extra code to judge if this param is post
````
if(isset($_POST['abc'])){
//checked,do some logic
}else{
//unchecked,do some logic
}
````
but the better way is use hidden input ,I can get the value without extra code,it simple and useful.
We should do like Html::checkbox() and the protected funcion booleanInput as[ doc](http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#booleanInput()-detail),I think should change InputWidget---getInput funciton,make sure checked status has his own option to set ,not  relation to  the value,value is the  receive post data,and should not decide the checked status.

**Comment by kartik-v** [comment] 2017-04-26 08:33
Yes IMO... that's the right way normally to write the logic as you posted based on checking if something is set in `$_POST` if you are using without a model. With model the `$model->load()` method does this in bulk. Note that hidden inputs can be tampered and changed by end user.

**Comment by nadirvishun** [comment] 2017-04-26 08:53
The security need to consider,but let us put security question aside, How to achieve the same result use switchinput Widget?
````
echo Html::checkbox('abc',1,['uncheck' => 0]);
````

**Comment by kartik-v** [comment] 2017-04-26 09:04
Just as I mentioned

```php
SwitchInput::widget(['name'=>'abc', 'value'=>1]);
```

and on your server controller action code that processes the above posted data

```php
$switchValue = Yii::$app->request->post('abc', '0');
```

**Comment by nadirvishun** [comment] 2017-04-26 09:16
@kartik-v 
no this simple .
there are two condition : if my db value is 1, can do like you wrritten above,but if my db value is 0 ,I have to do like this : 
````
SwitchInput::widget(['name'=>'abc', 'value'=>0]);//make suer status is unchecked 
````
````
$switchValue = Yii::$app->request->post('abc', 0);//if post ,abc value is 0,but I need is one ,so this is not work ,only can use isset($_POST['abc']) 
````
it's very complex,why we can not  do like this:
````
SwitchInput::widget(['name'=>'abc','options' => ['uncheck' => 0,'value'=>1,''checked'=>$value]]);
````

**Comment by kartik-v** [comment] 2017-04-26 09:21
Instead of 0 and 1 am stating the variables:

On your form view

```php
echo SwitchInput::widget(['name'=>'abc', 'value'=>DEFAULT_VAL]);
```

and on your server controller action code that processes the above posted data

```php
$switchValue = Yii::$app->request->post('abc', DEFAULT_VAL);
```

**Comment by nadirvishun** [comment] 2017-04-26 09:29
OMG!
It's not work well ,you can test  it in post form .

**Comment by kartik-v** [comment] 2017-04-26 10:04
Yes PHP does not receive the value of an UNCHECKED checkbox input via POST.... will figure out an enhancement.

**Comment by kartik-v** [comment] 2017-04-26 13:22
This is resolved in yii2-krajee-base now.

**Closed** 2017-04-26 13:21 UTC
Labels: enhancement

**Comment by nadirvishun** [comment] 2017-04-27 01:08
Thanks very much!It can work well use change code:
````
SwitchInput::widget([
                    'name' => 'abc',
                    'value' => $value,//checked status can change by db value
                    'options' => ['uncheck' => 0,'value'=>1],//value if not set ,default is 1
                ]);
````
